#!/usr/bin/env python3
"""
Krishna Interiors — gallery updater
-----------------------------------
Run this after adding/removing photos in gallery/images/.

  python3 update_gallery.py

How it works:
- Scans gallery/images/ (including sub-folders) for photos
  (.jpg .jpeg .png .webp .gif .svg)
- Sub-folder name becomes the Category  (e.g. gallery/images/kitchens/ -> "Kitchens")
- File name becomes the Title           (e.g. modular-kitchen-mg-road.jpg -> "Modular Kitchen Mg Road")
- Writes gallery/gallery.js, which the website reads automatically.

No other steps needed — just refresh the page in your browser.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent
IMAGES = ROOT / "gallery" / "images"
OUT = ROOT / "gallery" / "gallery.js"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg"}


def pretty(name: str) -> str:
    return name.replace("-", " ").replace("_", " ").strip().title()


def main():
    if not IMAGES.exists():
        IMAGES.mkdir(parents=True)
        print(f"Created {IMAGES} — add your photos there, then run this script again.")

    items = []
    for p in sorted(IMAGES.rglob("*")):
        if p.is_file() and p.suffix.lower() in EXTS:
            rel = p.relative_to(ROOT).as_posix()
            category = pretty(p.parent.name) if p.parent != IMAGES else "Projects"
            items.append({
                "src": rel,
                "title": pretty(p.stem),
                "category": category,
            })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by update_gallery.py — do not edit by hand.\n"
        "window.GALLERY = " + json.dumps(items, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} with {len(items)} photo(s).")
    if items:
        cats = sorted({i['category'] for i in items})
        print("Categories:", ", ".join(cats))
    else:
        print("No photos found yet. Add images to gallery/images/ and re-run.")


if __name__ == "__main__":
    main()
