// Auto-generated by update_gallery.py — do not edit by hand.
window.GALLERY = [
  {
    "src": "gallery/images/ceilings/gypsum-false-ceiling.svg",
    "title": "Gypsum False Ceiling",
    "category": "Ceilings"
  },
  {
    "src": "gallery/images/glass-works/shower-cubicle.svg",
    "title": "Shower Cubicle",
    "category": "Glass Works"
  },
  {
    "src": "gallery/images/glass-works/toughened-glass-partition.svg",
    "title": "Toughened Glass Partition",
    "category": "Glass Works"
  },
  {
    "src": "gallery/images/kitchens/modular-kitchen-vijayawada.svg",
    "title": "Modular Kitchen Vijayawada",
    "category": "Kitchens"
  },
  {
    "src": "gallery/images/kitchens/wardrobe-fit-out.svg",
    "title": "Wardrobe Fit Out",
    "category": "Kitchens"
  },
  {
    "src": "gallery/images/partitions/office-aluminium-partition.svg",
    "title": "Office Aluminium Partition",
    "category": "Partitions"
  }
];
